<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Logowanie</h3>
            </div>
            <div class="panel-body">
                <form enctype="multipart/form-data" action="<?= $this->url('signin'); ?>" method="post">
                    <fieldset>
                        <div class="form-group">
                            <input class="form-control" placeholder="E-mail" name="email" type="email" required>
                        </div>
                        <div class="form-group">
                            <input class="form-control" placeholder="Hasło" name="pwd" type="password" required>
                        </div>
                        <a href="<?= $this->url('signin'); ?>"><button type="submit" class="btn btn-lg btn-success">Zaloguj</button></a>
                    </fieldset>
                </form>
            </div>
            <div class="panel-footer">
                <a href="<?php echo $this->url('signup') ?>" class="btn btn-default">Rejestracja</a> <a href="" class="btn btn-default">Zapomniałem hasła</a>
            </div>
        </div>
    </div>
</div>