<div class="row">
    <h3 class="title">Lista newsów</h3>
    <hr>
</div>
<div class="row">
    <table class="table table-striped table-bordered table-hover" id="dataTables-example" style="width: 100%;">
        <thead>
            <tr>
                <th>ID</th>
                <th>Tytuł</th>
                <th>Kategoria</th>
                <th>Autor</th>
                <th>Data utworzenia</th>
                <th>Data ostatniej modyfikacji</th>
                <th>Znaznacz</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->all_news as $news) { ?>
            <tr>
                <td style="text-align: center;">
                    <?= $news['id_news'] ?>
                </td>
                <td>
                    <?= $news['title'] ?>
                </td>
                <td style="text-align: center;">
                    <?= $news['category'] ?>
                </td>
                <td>
                    <?= $news['author'] ?>
                </td>
                <td>
                    <?= $news['date_create'] ?>
                </td>
                <td>
                    <?= $news['date_modify'] ?>
                </td>
                <td style="text-align: center;">
                    <input type="checkbox" name="check" onclick="fun2(this)" value="<?= $news['id_news'] ?>">
                </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
    <script>
        var oryginal_edit = '';
        var oryginal_delete = '';
        
        var fun2 = function(cb)
        {
            var cbL = document.getElementsByName('check');
            var l = cbL.length;
            
            for(var i = 0; i<l; i++)
                if (cbL[i].checked)
                    if(cbL[i].value != cb.value)
                        cbL[i].checked = false;
            
            switch(cb.checked)
            {
                case true:
                    document.getElementById('news-edit').className = '';
                    oryginal_edit = (oryginal_edit == '') ? document.getElementById('news-edit-url').href : oryginal_edit;
                    document.getElementById('news-edit-url').href = oryginal_edit + '/' + cb.value;
                    
                    document.getElementById('news-delete').className = '';
                    oryginal_delete = (oryginal_delete == '') ? document.getElementById('news-delete-url').href : oryginal_delete;
                    document.getElementById('news-delete-url').href = oryginal_delete + '/' + cb.value;
                    break;
                    
                case false:
                    document.getElementById('news-edit').className = 'disabled';
                    document.getElementById('news-edit-url').href = oryginal_edit;
                    
                    document.getElementById('news-delete').className = 'disabled';
                    document.getElementById('news-delete-url').href = oryginal_delete;
                    break;
            }
        };
        
        var fun = function(rb)
        {
//            switch(rb.checked)
//            {
//                case true:
//                    rb.checked = false;
//                    document.getElementById('news-edit').className = 'disabled';
//                    document.getElementById('news-delete').className = 'disabled';
//                    break;
//                    
//                case false:
//                    rb.checked = true;
//                    document.getElementById('news-edit').className = '';
//                    document.getElementById('news-delete').className = '';
//                    break;
//            }
            if(rb.checked == false)
            {
                rb.checked = true;
                document.getElementById('news-edit').className = '';
                document.getElementById('news-delete').className = '';
                break;
            }
            if(rb.checked == true)
            {
                rb.checked = false;
                document.getElementById('news-edit').className = 'disabled';
                document.getElementById('news-delete').className = 'disabled';
                break;
            }
        };
//    function fun(radiobutton)
//    {
//        
//        if (radiobutton.checked)
//        {
//            radiobutton.checked = false;
//            document.getElementById('news-edit').className = 'disabled';
//            document.getElementById('news-delete').className = 'disabled';
//        }
//        else
//        {
//            document.getElementById('news-edit').className = '';
//            document.getElementById('news-delete').className = '';
//        }
//    }
    </script>
<!--    <script>
    $(document).ready(function() {
        
        $('#dataTables-example').DataTable({
            responsive: true,
            order: [[ 5, "desc" ]],
//            scrollY:        "200px",
//            scrollCollapse: true,
//            paging:         false,
            "language": {
                            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Polish.json"
                        }
//        language: {
//                    "lengthMenu": "Wyświetl _MENU_ pozycji na stronę",
//                    "zeroRecords": "Brak użytkowników spełniających kryteria",
//                    "info": "Strona _PAGE_ na _PAGES_",
//                    "infoEmpty": "Brak elementów",
//                    "infoFiltered": "(filtered from _MAX_ total records)"
//                }
        });
    });
    </script>-->
</div>