<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'public/image/vnd.microsoft.icon', 'href' => $this->basePath() . '/public/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('public/vendor/font-awesome/css/font-awesome.min.css')) 
                        ->prependStylesheet($this->basePath('public/vendor/morrisjs/morris.css'))
                        ->prependStylesheet($this->basePath('public/dist/css/sb-admin-2.css'))
                        ->prependStylesheet($this->basePath('public/vendor/metisMenu/metisMenu.min.css'))
                        ->prependStylesheet($this->basePath('public/vendor/bootstrap/css/bootstrap.min.css'))  
                ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile('https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile('https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div id="wrapper">
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">System CMS</a>
                </div>
                <ul class="nav navbar-top-links navbar-nav navbar-left">
                    <li>
                        <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
                    </li>
                    <li>
                        <a href="">Forum</a>
                    </li>
                </ul>
                <ul class="nav navbar-top-links navbar-nav navbar-right">
                    <?php if (!isset($this->user_name)) { ?>
                    <li><a href="<?php echo $this->url('signin') ?>">Logowanie</a></li>
                    <?php } else { ?>
                    <li><a href="<?php echo $this->url('signout') ?>">Wyloguj</a></li>
                    <?php } ?>
                </ul>
                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <?php if (isset($this->user_name)) {?>
                            <li style="text-align: center">
                                <?= $this->user_name ?><br>
                                [Ranga]<br>
                                [Avatar]<br>
                            </li>
                            <?php } ?>
                            <li>
                                <a href="<?php echo $this->url('signin') ?>"><i class="fa fa-comments"> Forum</i></a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
            </nav>
            <div id="page-wrapper">
                <?php echo $this->content; ?>
            </div>
<!--            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>-->
        </div> <!-- /container -->
        <?php echo $this->inlineScript()
            ->prependFile($this->basePath('public/dist/js/sb-admin-2.js'))
            ->prependFile($this->basePath('public/data/morris-data.js'))
            ->prependFile($this->basePath('public/vendor/morrisjs/morris.min.js'))
            ->prependFile($this->basePath('public/vendor/raphael/raphael.min.js'))
            ->prependFile($this->basePath('public/vendor/metisMenu/metisMenu.min.js'))
            ->prependFile($this->basePath('public/vendor/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('public/vendor/jquery/jquery.min.js')) ?>
    </body>
</html>
