<div class="row">
    <form enctype="multipart/form-data" action="<?= $this->url('adminuser',array('action' => 'Edit', 'id' => $id)); ?>" method="post">
        <div class="form-group input-group">
            <span class="input-group-addon">Nazwa użytkownika</span>
            <input type="text" name="name" placeholder="Nazwa użytkownika" class="form-control" required value="<?= $user->name ?>">
        </div>
        <div class="form-group input-group">
            <span class="input-group-addon">E-mail</span>
            <input disabled type="email" name="email" placeholder="E-mail" class="form-control" required value="<?= $user->email ?>">
        </div>
        <div class="form-group input-group">
            <span class="input-group-addon">Hasło</span>
            <input type="password" name="password" placeholder="Hasło" class="form-control">
        </div>
        <div class="form-group input-group">
            <span class="input-group-addon">Data urodzenia</span>
            <input type="date" name="date_birth" placeholder="Nazwa użytkownika" class="form-control" required value="<?= $user->date_birth ?>">
        </div>
        <div class="form-group input-group">
            <span class="input-group-addon">Grupa</span>
            <select name="group" class="form-control" required pattern="(?=.*[0-9])(?=.*[0-9])">
                <option disabled selected value="">Wybierz grupę</option>
                <?php foreach($groups as $group) { ?>
                <option value="<?= $group->id_group ?>" <?= ($user->id_group == $group->id_group)?"selected":"" ?>><?= $group->name ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="form-group">
            <a href="<?= $this->url('adminuser', array('action' => 'Edit', 'id' => $id)) ?>"><button type="submit" class="btn btn-success">Edytuj</button></a>
        </div>
    </form>
</div>