<div class="row">
    <h3 class="title">Panel Administratora</h3>
</div>
<div class="row">
    <div class="col-lg-3">
        <a href="<?= $this->url('adminuser') ?>" class="btn btn-default btn-lg btn-block"><i class="fa fa-user"> Użytkownicy</i></a>
    </div>
    <div class="col-lg-3">
        <a href="" class="btn btn-default btn-lg btn-block"><i class="fa fa-user"> Forum</i></a>
    </div>
    <div class="col-lg-3">
        <a href="" class="btn btn-default btn-lg btn-block"><i class="fa fa-user"> Newsy</i></a>
    </div>
    <div class="col-lg-3">
        <a href="" class="btn btn-default btn-lg btn-block"><i class="fa fa-user"> Komentarze</i></a>
    </div>
</div>