<div class="row">
<!--    <div class="col-lg-6 col-md-offset-2">-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Tytuł news'a</h3>
            </div>
            <div class="panel-heading">
                <i class="fa fa-calendar"> 05-11-2016</i> <i class="fa fa-user"> Autor</i>
            </div>
            <div class="panel-body">
                Treść news'a
            </div>
            <div class="panel-footer">
                <a href="" class="btn btn-default">Czytaj więcej</a> <a href="" class="btn btn-default">Komentarze (ilość)</a>
            </div>
        </div>
    </div>
<!--</div>-->